### ISSUE TITLE
感谢分享，然后想问下我相册里有一些大图（十几兆的那种），在这个选择器里显示不出来，是哪里做了限制吗？

### ISSUE THREAD

**Issue by gaojiewan** [CheeryLau/MMPhotoPicker#1]
感谢分享，然后想问下我相册里有一些大图（十几兆的那种），在这个选择器里显示不出来，是哪里做了限制吗？

**Comment by ChaneyLau** [comment]
> 感谢分享，然后想问下我相册里有一些大图（十几兆的那种），在这个选择器里显示不出来，是哪里做了限制吗？

最新版本试一下。
