### ISSUE TITLE
请再次上传MMCaptchaView

### ISSUE THREAD

**Issue by mash3l777** [CheeryLau/MMPhotoPicker#3]
我用过它的精彩

**Comment by ChaneyLau** [comment]
> 我用过它的精彩

哈哈哈哈，好的，欢迎使用。

**Comment by mash3l777** [comment]
where that repository now ?
现在哪个存储库？

**Comment by ChaneyLau** [comment]
> where that repository now ?
> 现在哪个存储库？

链接：https://github.com/ChellyLau/MMCaptchaView
